#!/bin/bash

# PREFIX_IP="10.89"

cat <<EOF > /etc/network/interfaces
# This file is auto-generated by setup script
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

auto eth1
iface eth1 inet static
    address 10.89.17.1
    netmask 255.255.255.0

auto eth2
iface eth2 inet static
    address 10.89.30.1
    netmask 255.255.255.0
EOF

apt update
apt install -y iptables
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE -s 10.89.0.0/16
cat /etc/resolv.conf
