#!/bin/bash

# PREFIX_IP="10.89"

# NOMOR 2
cat <<EOF > /etc/network/interfaces
# This file is auto-generated by setup script
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

auto eth1
iface eth1 inet static
    address 10.89.17.1
    netmask 255.255.255.0

auto eth2
iface eth2 inet static
    address 10.89.30.1
    netmask 255.255.255.0
EOF

# NOMOR 3
apt update #masukin bashrc
apt install -y iptables #masukin bashrc
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE -s 10.89.0.0/16 #masukin bashrc
# cat /etc/resolv.conf

#NOMOR 7
# CONFIG VSFTPD
apt install -y vsftpd 

# ADD 2 USER MELKOR (NO ACCESS) AND AINUR (READ WRITE)
adduser melkor 
adduser ainur 
echo "melkor" | tee -a /etc/vsftpd.userlist

# CREATE SHARED FOLDER & SET PERMISSIONS
mkdir -p /srv/ftp/shared
chown -R ainur:ainur /srv/ftp/shared
chmod -R 700 /srv/ftp/shared

# CONFIG VSFTPD
# write_enable=YES
# chroot_local_user=NO
# chroot_list_enable=YES
# chroot_list_file=/etc/vsftpd.userlist
# local_root=/srv/ftp/shared
# userlist_enable=YES
# userlist_file=/etc/vsftpd.userlist
# userlist_deny=YES
service vsftpd restart

# NOMOR 9
wget --no-check-certificate "https://docs.google.com/uc?export=download&id=11ua2KgBu3MnHEIjhBnzqqv2RMEiJsILY" -O /srv/ftp/shared/kitab_penciptaan.zip

# change ftp permission to read only (cannot upload file)
chmod 500 /srv/ftp/shared
# write_enable=NO
service vsftpd restart

# NOMOR 11
telnet 10.89.17.30


# NOMOR 12
nc -vz -w2 10.89.17.30 21
nc -vz -w2 10.89.17.30 80
nc -vz -w2 10.89.17.30 666

# NOMOR 13
adduser varda
apt install -y openssh-server
service ssh start
