#!/bin/bash

# PREFIX_IP="10.89"

# NOMOR 3
cat <<EOF > /etc/network/interfaces
# This file is auto-generated by setup script
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
	address 10.89.17.17
	netmask 255.255.255.0
	gateway 10.89.17.1
EOF 

echo nameserver 192.168.122.1 > /etc/resolv.conf # masukin bashrc

# NOMOR 6
cat <<EOF > traffic.sh
#!/bin/bash

echo "Memulai pembuatan traffic jaringan selama 10 detik..."

cleanup() {
    echo ""
    echo "Menghentikan semua proses pembuat traffic..."
    kill $(jobs -p) > /dev/null 2>&1
    echo "Selesai."
}

trap cleanup EXIT

ping -i 0.1 8.8.8.8 > /dev/null 2>&1 &

wget -qO /dev/null http://speedtest.tele2.net/10MB.zip &
wget -qO /dev/null http://proof.ovh.net/files/10Mb.dat &

nmap -T4 -F scanme.nmap.org > /dev/null 2>&1 &

sleep 10

EOF

chmod +x traffic.sh
./traffic.sh

# NOMOR 9
# ftp 192.168.122.64
# get kitab_penciptaan.zip
# bye

# TES PERMISSION
echo "tes" > tes.txt
ftp 192.168.122.64
put tes.txt
bye



