#!/bin/bash

# PREFIX_IP="10.89"

cat <<EOF > /etc/network/interfaces
# This file is auto-generated by setup script
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
	address 10.89.17.30
	netmask 255.255.255.0
	gateway 10.89.17.1
EOF

echo nameserver 192.168.122.1 > /etc/resolv.conf