#!/bin/bash

# PREFIX_IP="10.89"

# NOMOR 3
cat <<EOF > /etc/network/interfaces
# This file is auto-generated by setup script
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
	address 10.89.17.30
	netmask 255.255.255.0
	gateway 10.89.17.1
EOF 

echo nameserver 192.168.122.1 > /etc/resolv.conf # masukin bashrc

# NOMOR 10
ping 192.168.122.64 -c 100


# NOMOR 11
adduser eru
apt install telnetd
apt install openbsd-inetd
echo "telnet stream tcp nowait root /usr/sbin/tcpd /usr/sbin/telnetd" >> /etc/inetd.conf
service openbsd-inetd restart


# NOMOR 12
apt install netcat-openbsd
nc -l 21 >/dev/null 2>&1 &
nc -l 80 >/dev/null 2>&1 &
