#!/bin/bash

# PREFIX_IP="10.89"

# NOMOR 3
cat <<EOF > /etc/network/interfaces
# This file is auto-generated by setup script
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
	address 10.89.30.30
	netmask 255.255.255.0
	gateway 10.89.30.1
EOF 

echo nameserver 192.168.122.1 > /etc/resolv.conf # masukin bashrc

# NOMOR 8
apt update
apt install -y inetutils-ftp

wget --no-check-certificate "https://docs.google.com/uc?export=download&id=11ra_yTV_adsPIXeIPMSt0vrxCBZu0r33" -O cuaca.zip


# ftp 192.168.122.64
# put cuaca.zip
# bye


