#!/bin/bash

# PREFIX_IP="10.89"

# NOMOR 3
cat <<EOF > /etc/network/interfaces
# This file is auto-generated by setup script
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
	address 10.89.30.17
	netmask 255.255.255.0
	gateway 10.89.30.1
EOF 

echo nameserver 192.168.122.1 > /etc/resolv.conf # masukin bashrc

# NOMOR 13
ssh varda@192.168.122.64
